#!/bin/sh

RED='\033[0;31m'
NC='\033[0m' # No Color

sudo apt install build-essential cmake git libpoco-dev libeigen3-dev -y

# For protoc
sudo apt-get install autoconf automake libtool curl make g++ unzip -y

# For zmq
sudo apt-get install libzmq3-dev -y

# download libfranka
git clone --recursive https://github.com/frankaemika/libfranka
cd libfranka

# hsc: we use libfranka 0.8.0
git checkout 0.8.0

git submodule update
cd ..

# download c++ zmq wrapper
git clone https://github.com/zeromq/zmqpp.git

# download yaml cpp package
git clone https://github.com/jbeder/yaml-cpp.git

# download spdlog package
git clone https://github.com/gabime/spdlog.git
cd spdlog
git checkout ac55e60488032b9acde8940a5de099541c4515da
cd ..

# download protobuf
git clone --recursive https://github.com/protocolbuffers/protobuf.git
cd protobuf
git checkout v5.28.3
git submodule update

./autogen.sh
./configure
make
make check
sudo make install
sudo ldconfig # refresh shared library cache.

# Install other apt packages
sudo apt install libreadline-dev -y
sudo apt install bzip2 -y
sudo apt install libmotif-dev libglfw3 -y
