#!/bin/sh

RED='\033[0;31m'
NC='\033[0m' # No Color

sudo apt install build-essential cmake git libpoco-dev libeigen3-dev -y

# For protoc
sudo apt-get install autoconf automake libtool curl make g++ unzip -y

# For zmq
sudo apt-get install libzmq3-dev -y

# download libfranka
git clone --recursive https://github.com/frankaemika/libfranka
cd libfranka

# NOTE (hsc): we use libfranka 0.15.3 for franka research 3
# and libfranka 0.8.0 for the old franka arm.
# for libfranka 0.14.0 or later, we also need to install pinocchio
# https://github.com/frankarobotics/libfranka?tab=readme-ov-file#2-installing-dependencies
git checkout 0.15.3

git submodule update
cd ..

# NOTE (hsc): It seems we still need to install zmqpp system-wide.
# sudo apt-get install libzmq3-dev
# download c++ zmq wrapper
git clone https://github.com/zeromq/zmqpp.git

# download yaml cpp package
git clone https://github.com/jbeder/yaml-cpp.git

# download spdlog package
git clone https://github.com/gabime/spdlog.git
cd spdlog
git checkout ac55e60488032b9acde8940a5de099541c4515da
cd ..

# NOTE (hsc): we use system-installed protobuf instead of building from source
# In my case, it is protobuf 3.12.4

# Install other apt packages
sudo apt install libreadline-dev -y
sudo apt install bzip2 -y
sudo apt install libmotif-dev libglfw3 -y
